//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Happystore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_details
    {
        public int id { get; set; }
        public int Product_id { get; set; }
        public int Order_id { get; set; }
        public int Quantity { get; set; }
        public string Cus_image { get; set; }
        public string Cus_Name { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
