//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Happystore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Order_details = new HashSet<Order_details>();
            this.Shoping_Cart = new HashSet<Shoping_Cart>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string Discription { get; set; }
        public string Price { get; set; }
        public string Image { get; set; }
        public string Video { get; set; }
        public int Sub_Categorie_id { get; set; }
        public bool Need_image { get; set; }
        public bool Need_Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_details> Order_details { get; set; }
        public virtual Sub_Category Sub_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shoping_Cart> Shoping_Cart { get; set; }
    }
}
