//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Happystore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shoping_Cart
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int product_id { get; set; }
        public string Cus_image { get; set; }
        public string Cus_name { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
